name: main

on:
  pull_request:
  # `workflow_call` is used by the tag workflow to trigger the `build` job
  workflow_call:
  workflow_dispatch:

jobs:
  check-codingstyle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: ci/install-clang-format
      - name: check coding style
        run: CLANG_FORMAT_CMD=./clang-format ci/check-codingstyle

  build:
    runs-on: ${{ matrix.os }}
    env:
      PYTHONUNBUFFERED: 1
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-12
          - windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: ci/install-dependencies deps
        shell: bash
      - name: Build
        run: . deps/env.sh && ci/build-app
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/nanonote[-_]*.*
